# Generated by Django 4.0.4 on 2022-06-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
